/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmergencyContact = IDL.Record({
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const Medication = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'dose' : IDL.Text,
  'name' : IDL.Text,
  'instructions' : IDL.Text,
  'schedule' : IDL.Vec(IDL.Text),
  'prescriber' : IDL.Text,
  'startDate' : IDL.Opt(Time),
});
export const Meeting = IDL.Record({
  'date' : Time,
  'goals' : IDL.Text,
  'notes' : IDL.Text,
  'sponsorContactNotes' : IDL.Text,
  'format' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CombineResult = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'dash10yd' : IDL.Opt(IDL.Float64),
  'dash20yd' : IDL.Opt(IDL.Float64),
  'dash40yd' : IDL.Opt(IDL.Float64),
  'heightInches' : IDL.Opt(IDL.Nat),
  'wingspanInches' : IDL.Opt(IDL.Float64),
  'threeConeDrill' : IDL.Opt(IDL.Float64),
  'handSizeInches' : IDL.Opt(IDL.Float64),
  'weightPounds' : IDL.Opt(IDL.Nat),
  'benchPressReps' : IDL.Opt(IDL.Nat),
  'broadJumpInches' : IDL.Opt(IDL.Float64),
  'shuttle20yd' : IDL.Opt(IDL.Float64),
  'timestamp' : Time,
  'isPublic' : IDL.Bool,
  'verticalJumpInches' : IDL.Opt(IDL.Float64),
  'athleteName' : IDL.Text,
});
export const RecoveryStep = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CheckIn = IDL.Record({
  'stressLevel' : IDL.Nat,
  'mood' : IDL.Text,
  'timestamp' : Time,
  'reflection' : IDL.Text,
  'workHours' : IDL.Nat,
  'intention' : IDL.Text,
});
export const CommitmentsPlan = IDL.Record({
  'thingsToAvoid' : IDL.Text,
  'atRiskActions' : IDL.Text,
  'personalCommitments' : IDL.Text,
});
export const DoseLog = IDL.Record({
  'status' : IDL.Variant({
    'Skipped' : IDL.Null,
    'Late' : IDL.Null,
    'Taken' : IDL.Null,
  }),
  'medicationName' : IDL.Text,
  'scheduledTime' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'takenTime' : IDL.Opt(Time),
  'timestamp' : Time,
});
export const Reflection = IDL.Record({
  'id' : IDL.Nat,
  'stepId' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmergencyContact' : IDL.Func([EmergencyContact], [], []),
  'addMedication' : IDL.Func([Medication], [], []),
  'addMeeting' : IDL.Func([Meeting], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCombineResult' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllPublicCombineEntries' : IDL.Func(
      [],
      [IDL.Vec(CombineResult)],
      ['query'],
    ),
  'getAllRecoverySteps' : IDL.Func([], [IDL.Vec(RecoveryStep)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'getCombineResultById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CombineResult)],
      ['query'],
    ),
  'getCommitmentsPlan' : IDL.Func([], [IDL.Opt(CommitmentsPlan)], ['query']),
  'getDoseLogs' : IDL.Func([], [IDL.Vec(DoseLog)], ['query']),
  'getEmergencyContacts' : IDL.Func([], [IDL.Vec(EmergencyContact)], ['query']),
  'getMedications' : IDL.Func([], [IDL.Vec(Medication)], ['query']),
  'getMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
  'getReflections' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
  'getUserCombineResults' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CombineResult)],
      ['query'],
    ),
  'getUserData' : IDL.Func(
      [],
      [
        IDL.Record({
          'meetings' : IDL.Vec(Meeting),
          'emergencyContacts' : IDL.Vec(EmergencyContact),
          'reflections' : IDL.Vec(Reflection),
          'medications' : IDL.Vec(Medication),
          'checkIns' : IDL.Vec(CheckIn),
          'doseLogs' : IDL.Vec(DoseLog),
          'commitmentsPlan' : IDL.Opt(CommitmentsPlan),
          'recoverySteps' : IDL.Vec(RecoveryStep),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logCheckIn' : IDL.Func([CheckIn], [], []),
  'logDose' : IDL.Func([DoseLog], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCombineResult' : IDL.Func(
      [
        IDL.Record({
          'dash10yd' : IDL.Opt(IDL.Float64),
          'dash20yd' : IDL.Opt(IDL.Float64),
          'dash40yd' : IDL.Opt(IDL.Float64),
          'heightInches' : IDL.Opt(IDL.Nat),
          'wingspanInches' : IDL.Opt(IDL.Float64),
          'threeConeDrill' : IDL.Opt(IDL.Float64),
          'handSizeInches' : IDL.Opt(IDL.Float64),
          'weightPounds' : IDL.Opt(IDL.Nat),
          'benchPressReps' : IDL.Opt(IDL.Nat),
          'broadJumpInches' : IDL.Opt(IDL.Float64),
          'shuttle20yd' : IDL.Opt(IDL.Float64),
          'makePublic' : IDL.Bool,
          'verticalJumpInches' : IDL.Opt(IDL.Float64),
          'athleteName' : IDL.Text,
        }),
      ],
      [CombineResult],
      [],
    ),
  'saveCommitmentsPlan' : IDL.Func([CommitmentsPlan], [], []),
  'saveReflection' : IDL.Func([Reflection], [], []),
  'toggleCombinePublicState' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmergencyContact = IDL.Record({
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const Medication = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'dose' : IDL.Text,
    'name' : IDL.Text,
    'instructions' : IDL.Text,
    'schedule' : IDL.Vec(IDL.Text),
    'prescriber' : IDL.Text,
    'startDate' : IDL.Opt(Time),
  });
  const Meeting = IDL.Record({
    'date' : Time,
    'goals' : IDL.Text,
    'notes' : IDL.Text,
    'sponsorContactNotes' : IDL.Text,
    'format' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CombineResult = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'dash10yd' : IDL.Opt(IDL.Float64),
    'dash20yd' : IDL.Opt(IDL.Float64),
    'dash40yd' : IDL.Opt(IDL.Float64),
    'heightInches' : IDL.Opt(IDL.Nat),
    'wingspanInches' : IDL.Opt(IDL.Float64),
    'threeConeDrill' : IDL.Opt(IDL.Float64),
    'handSizeInches' : IDL.Opt(IDL.Float64),
    'weightPounds' : IDL.Opt(IDL.Nat),
    'benchPressReps' : IDL.Opt(IDL.Nat),
    'broadJumpInches' : IDL.Opt(IDL.Float64),
    'shuttle20yd' : IDL.Opt(IDL.Float64),
    'timestamp' : Time,
    'isPublic' : IDL.Bool,
    'verticalJumpInches' : IDL.Opt(IDL.Float64),
    'athleteName' : IDL.Text,
  });
  const RecoveryStep = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CheckIn = IDL.Record({
    'stressLevel' : IDL.Nat,
    'mood' : IDL.Text,
    'timestamp' : Time,
    'reflection' : IDL.Text,
    'workHours' : IDL.Nat,
    'intention' : IDL.Text,
  });
  const CommitmentsPlan = IDL.Record({
    'thingsToAvoid' : IDL.Text,
    'atRiskActions' : IDL.Text,
    'personalCommitments' : IDL.Text,
  });
  const DoseLog = IDL.Record({
    'status' : IDL.Variant({
      'Skipped' : IDL.Null,
      'Late' : IDL.Null,
      'Taken' : IDL.Null,
    }),
    'medicationName' : IDL.Text,
    'scheduledTime' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'takenTime' : IDL.Opt(Time),
    'timestamp' : Time,
  });
  const Reflection = IDL.Record({
    'id' : IDL.Nat,
    'stepId' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmergencyContact' : IDL.Func([EmergencyContact], [], []),
    'addMedication' : IDL.Func([Medication], [], []),
    'addMeeting' : IDL.Func([Meeting], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCombineResult' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllPublicCombineEntries' : IDL.Func(
        [],
        [IDL.Vec(CombineResult)],
        ['query'],
      ),
    'getAllRecoverySteps' : IDL.Func([], [IDL.Vec(RecoveryStep)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'getCombineResultById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CombineResult)],
        ['query'],
      ),
    'getCommitmentsPlan' : IDL.Func([], [IDL.Opt(CommitmentsPlan)], ['query']),
    'getDoseLogs' : IDL.Func([], [IDL.Vec(DoseLog)], ['query']),
    'getEmergencyContacts' : IDL.Func(
        [],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'getMedications' : IDL.Func([], [IDL.Vec(Medication)], ['query']),
    'getMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
    'getReflections' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
    'getUserCombineResults' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CombineResult)],
        ['query'],
      ),
    'getUserData' : IDL.Func(
        [],
        [
          IDL.Record({
            'meetings' : IDL.Vec(Meeting),
            'emergencyContacts' : IDL.Vec(EmergencyContact),
            'reflections' : IDL.Vec(Reflection),
            'medications' : IDL.Vec(Medication),
            'checkIns' : IDL.Vec(CheckIn),
            'doseLogs' : IDL.Vec(DoseLog),
            'commitmentsPlan' : IDL.Opt(CommitmentsPlan),
            'recoverySteps' : IDL.Vec(RecoveryStep),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logCheckIn' : IDL.Func([CheckIn], [], []),
    'logDose' : IDL.Func([DoseLog], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCombineResult' : IDL.Func(
        [
          IDL.Record({
            'dash10yd' : IDL.Opt(IDL.Float64),
            'dash20yd' : IDL.Opt(IDL.Float64),
            'dash40yd' : IDL.Opt(IDL.Float64),
            'heightInches' : IDL.Opt(IDL.Nat),
            'wingspanInches' : IDL.Opt(IDL.Float64),
            'threeConeDrill' : IDL.Opt(IDL.Float64),
            'handSizeInches' : IDL.Opt(IDL.Float64),
            'weightPounds' : IDL.Opt(IDL.Nat),
            'benchPressReps' : IDL.Opt(IDL.Nat),
            'broadJumpInches' : IDL.Opt(IDL.Float64),
            'shuttle20yd' : IDL.Opt(IDL.Float64),
            'makePublic' : IDL.Bool,
            'verticalJumpInches' : IDL.Opt(IDL.Float64),
            'athleteName' : IDL.Text,
          }),
        ],
        [CombineResult],
        [],
      ),
    'saveCommitmentsPlan' : IDL.Func([CommitmentsPlan], [], []),
    'saveReflection' : IDL.Func([Reflection], [], []),
    'toggleCombinePublicState' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };