/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmergencyContact = IDL.Record({
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const Medication = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'dose' : IDL.Text,
  'name' : IDL.Text,
  'instructions' : IDL.Text,
  'schedule' : IDL.Vec(IDL.Text),
  'prescriber' : IDL.Text,
  'startDate' : IDL.Opt(Time),
});
export const Meeting = IDL.Record({
  'date' : Time,
  'goals' : IDL.Text,
  'notes' : IDL.Text,
  'sponsorContactNotes' : IDL.Text,
  'format' : IDL.Text,
});
export const SubscriptionStatus = IDL.Variant({
  'Active' : Time,
  'Expired' : IDL.Null,
  'Pending' : IDL.Null,
});
export const UserProfileWithPrincipal = IDL.Record({
  'principal' : IDL.Principal,
  'hasPaid' : IDL.Bool,
  'name' : IDL.Text,
  'subscriptionStatus' : SubscriptionStatus,
  'isAdmin' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CombineMeasurement = IDL.Record({
  'verified' : IDL.Bool,
  'value' : IDL.Opt(IDL.Float64),
  'equipmentUsed' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'measurementType' : IDL.Text,
  'attemptNumber' : IDL.Opt(IDL.Nat),
});
export const CombineResult = IDL.Record({
  'id' : IDL.Nat,
  'bmi' : CombineMeasurement,
  'weight' : CombineMeasurement,
  'passedMedical' : IDL.Bool,
  'height' : CombineMeasurement,
  'powerClean' : CombineMeasurement,
  'verticalJump' : CombineMeasurement,
  'creator' : IDL.Principal,
  'dash10yd' : CombineMeasurement,
  'dash20yd' : CombineMeasurement,
  'dash40yd' : CombineMeasurement,
  'wingspan' : CombineMeasurement,
  'threeConeDrill' : CombineMeasurement,
  'benchPressReps' : CombineMeasurement,
  'squat' : CombineMeasurement,
  'developerNotes' : IDL.Opt(IDL.Text),
  'shuttleProAgility' : CombineMeasurement,
  'shuttle20yd' : CombineMeasurement,
  'timestamp' : Time,
  'shuttle60yd' : CombineMeasurement,
  'isPublic' : IDL.Bool,
  'handSize' : CombineMeasurement,
  'broadJump' : CombineMeasurement,
  'seatedRow' : CombineMeasurement,
  'athleteName' : IDL.Text,
  'armLength' : CombineMeasurement,
  'standingReach' : CombineMeasurement,
  'bodyFatPercentage' : CombineMeasurement,
});
export const RecoveryStep = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
});
export const CallerUserProfile = IDL.Record({
  'hasPaid' : IDL.Bool,
  'name' : IDL.Text,
  'subscriptionStatus' : SubscriptionStatus,
  'isAdmin' : IDL.Bool,
});
export const CheckIn = IDL.Record({
  'stressLevel' : IDL.Nat,
  'mood' : IDL.Text,
  'timestamp' : Time,
  'reflection' : IDL.Text,
  'workHours' : IDL.Nat,
  'intention' : IDL.Text,
});
export const CommitmentsPlan = IDL.Record({
  'thingsToAvoid' : IDL.Text,
  'atRiskActions' : IDL.Text,
  'personalCommitments' : IDL.Text,
});
export const DoseLog = IDL.Record({
  'status' : IDL.Variant({
    'Skipped' : IDL.Null,
    'Late' : IDL.Null,
    'Taken' : IDL.Null,
  }),
  'medicationName' : IDL.Text,
  'scheduledTime' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'takenTime' : IDL.Opt(Time),
  'timestamp' : Time,
});
export const Reflection = IDL.Record({
  'id' : IDL.Nat,
  'stepId' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmergencyContact' : IDL.Func([EmergencyContact], [], []),
  'addMedication' : IDL.Func([Medication], [], []),
  'addMeeting' : IDL.Func([Meeting], [], []),
  'adminListAllUsers' : IDL.Func(
      [],
      [IDL.Vec(UserProfileWithPrincipal)],
      ['query'],
    ),
  'adminSetUserSubscription' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkSubscriptionActive' : IDL.Func([], [IDL.Bool], ['query']),
  'deleteCombineResult' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllPublicCombineEntries' : IDL.Func(
      [],
      [IDL.Vec(CombineResult)],
      ['query'],
    ),
  'getAllRecoverySteps' : IDL.Func([], [IDL.Vec(RecoveryStep)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(CallerUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'getCombineResultById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CombineResult)],
      ['query'],
    ),
  'getCommitmentsPlan' : IDL.Func([], [IDL.Opt(CommitmentsPlan)], ['query']),
  'getDoseLogs' : IDL.Func([], [IDL.Vec(DoseLog)], ['query']),
  'getEmergencyContacts' : IDL.Func([], [IDL.Vec(EmergencyContact)], ['query']),
  'getMedications' : IDL.Func([], [IDL.Vec(Medication)], ['query']),
  'getMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
  'getReflections' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
  'getUserCombineResults' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CombineResult)],
      ['query'],
    ),
  'getUserData' : IDL.Func(
      [],
      [
        IDL.Record({
          'meetings' : IDL.Vec(Meeting),
          'emergencyContacts' : IDL.Vec(EmergencyContact),
          'reflections' : IDL.Vec(Reflection),
          'medications' : IDL.Vec(Medication),
          'checkIns' : IDL.Vec(CheckIn),
          'doseLogs' : IDL.Vec(DoseLog),
          'commitmentsPlan' : IDL.Opt(CommitmentsPlan),
          'recoverySteps' : IDL.Vec(RecoveryStep),
        }),
      ],
      ['query'],
    ),
  'getUserPaymentStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CallerUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logCheckIn' : IDL.Func([CheckIn], [], []),
  'logDose' : IDL.Func([DoseLog], [], []),
  'saveCallerUserProfile' : IDL.Func([CallerUserProfile], [], []),
  'saveCombineResult' : IDL.Func(
      [
        IDL.Record({
          'bmi' : CombineMeasurement,
          'weight' : CombineMeasurement,
          'passedMedical' : IDL.Bool,
          'height' : CombineMeasurement,
          'powerClean' : CombineMeasurement,
          'verticalJump' : CombineMeasurement,
          'dash10yd' : CombineMeasurement,
          'dash20yd' : CombineMeasurement,
          'dash40yd' : CombineMeasurement,
          'wingspan' : CombineMeasurement,
          'threeConeDrill' : CombineMeasurement,
          'benchPressReps' : CombineMeasurement,
          'squat' : CombineMeasurement,
          'developerNotes' : IDL.Opt(IDL.Text),
          'shuttleProAgility' : CombineMeasurement,
          'shuttle20yd' : CombineMeasurement,
          'shuttle60yd' : CombineMeasurement,
          'makePublic' : IDL.Bool,
          'handSize' : CombineMeasurement,
          'broadJump' : CombineMeasurement,
          'seatedRow' : CombineMeasurement,
          'athleteName' : IDL.Text,
          'armLength' : CombineMeasurement,
          'standingReach' : CombineMeasurement,
          'bodyFatPercentage' : CombineMeasurement,
        }),
      ],
      [CombineResult],
      [],
    ),
  'saveCommitmentsPlan' : IDL.Func([CommitmentsPlan], [], []),
  'saveReflection' : IDL.Func([Reflection], [], []),
  'toggleCombinePublicState' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'togglePaymentStatus' : IDL.Func([IDL.Principal], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmergencyContact = IDL.Record({
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const Medication = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'dose' : IDL.Text,
    'name' : IDL.Text,
    'instructions' : IDL.Text,
    'schedule' : IDL.Vec(IDL.Text),
    'prescriber' : IDL.Text,
    'startDate' : IDL.Opt(Time),
  });
  const Meeting = IDL.Record({
    'date' : Time,
    'goals' : IDL.Text,
    'notes' : IDL.Text,
    'sponsorContactNotes' : IDL.Text,
    'format' : IDL.Text,
  });
  const SubscriptionStatus = IDL.Variant({
    'Active' : Time,
    'Expired' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const UserProfileWithPrincipal = IDL.Record({
    'principal' : IDL.Principal,
    'hasPaid' : IDL.Bool,
    'name' : IDL.Text,
    'subscriptionStatus' : SubscriptionStatus,
    'isAdmin' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CombineMeasurement = IDL.Record({
    'verified' : IDL.Bool,
    'value' : IDL.Opt(IDL.Float64),
    'equipmentUsed' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'measurementType' : IDL.Text,
    'attemptNumber' : IDL.Opt(IDL.Nat),
  });
  const CombineResult = IDL.Record({
    'id' : IDL.Nat,
    'bmi' : CombineMeasurement,
    'weight' : CombineMeasurement,
    'passedMedical' : IDL.Bool,
    'height' : CombineMeasurement,
    'powerClean' : CombineMeasurement,
    'verticalJump' : CombineMeasurement,
    'creator' : IDL.Principal,
    'dash10yd' : CombineMeasurement,
    'dash20yd' : CombineMeasurement,
    'dash40yd' : CombineMeasurement,
    'wingspan' : CombineMeasurement,
    'threeConeDrill' : CombineMeasurement,
    'benchPressReps' : CombineMeasurement,
    'squat' : CombineMeasurement,
    'developerNotes' : IDL.Opt(IDL.Text),
    'shuttleProAgility' : CombineMeasurement,
    'shuttle20yd' : CombineMeasurement,
    'timestamp' : Time,
    'shuttle60yd' : CombineMeasurement,
    'isPublic' : IDL.Bool,
    'handSize' : CombineMeasurement,
    'broadJump' : CombineMeasurement,
    'seatedRow' : CombineMeasurement,
    'athleteName' : IDL.Text,
    'armLength' : CombineMeasurement,
    'standingReach' : CombineMeasurement,
    'bodyFatPercentage' : CombineMeasurement,
  });
  const RecoveryStep = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
  });
  const CallerUserProfile = IDL.Record({
    'hasPaid' : IDL.Bool,
    'name' : IDL.Text,
    'subscriptionStatus' : SubscriptionStatus,
    'isAdmin' : IDL.Bool,
  });
  const CheckIn = IDL.Record({
    'stressLevel' : IDL.Nat,
    'mood' : IDL.Text,
    'timestamp' : Time,
    'reflection' : IDL.Text,
    'workHours' : IDL.Nat,
    'intention' : IDL.Text,
  });
  const CommitmentsPlan = IDL.Record({
    'thingsToAvoid' : IDL.Text,
    'atRiskActions' : IDL.Text,
    'personalCommitments' : IDL.Text,
  });
  const DoseLog = IDL.Record({
    'status' : IDL.Variant({
      'Skipped' : IDL.Null,
      'Late' : IDL.Null,
      'Taken' : IDL.Null,
    }),
    'medicationName' : IDL.Text,
    'scheduledTime' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'takenTime' : IDL.Opt(Time),
    'timestamp' : Time,
  });
  const Reflection = IDL.Record({
    'id' : IDL.Nat,
    'stepId' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmergencyContact' : IDL.Func([EmergencyContact], [], []),
    'addMedication' : IDL.Func([Medication], [], []),
    'addMeeting' : IDL.Func([Meeting], [], []),
    'adminListAllUsers' : IDL.Func(
        [],
        [IDL.Vec(UserProfileWithPrincipal)],
        ['query'],
      ),
    'adminSetUserSubscription' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkSubscriptionActive' : IDL.Func([], [IDL.Bool], ['query']),
    'deleteCombineResult' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllPublicCombineEntries' : IDL.Func(
        [],
        [IDL.Vec(CombineResult)],
        ['query'],
      ),
    'getAllRecoverySteps' : IDL.Func([], [IDL.Vec(RecoveryStep)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(CallerUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'getCombineResultById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CombineResult)],
        ['query'],
      ),
    'getCommitmentsPlan' : IDL.Func([], [IDL.Opt(CommitmentsPlan)], ['query']),
    'getDoseLogs' : IDL.Func([], [IDL.Vec(DoseLog)], ['query']),
    'getEmergencyContacts' : IDL.Func(
        [],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'getMedications' : IDL.Func([], [IDL.Vec(Medication)], ['query']),
    'getMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
    'getReflections' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
    'getUserCombineResults' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CombineResult)],
        ['query'],
      ),
    'getUserData' : IDL.Func(
        [],
        [
          IDL.Record({
            'meetings' : IDL.Vec(Meeting),
            'emergencyContacts' : IDL.Vec(EmergencyContact),
            'reflections' : IDL.Vec(Reflection),
            'medications' : IDL.Vec(Medication),
            'checkIns' : IDL.Vec(CheckIn),
            'doseLogs' : IDL.Vec(DoseLog),
            'commitmentsPlan' : IDL.Opt(CommitmentsPlan),
            'recoverySteps' : IDL.Vec(RecoveryStep),
          }),
        ],
        ['query'],
      ),
    'getUserPaymentStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CallerUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logCheckIn' : IDL.Func([CheckIn], [], []),
    'logDose' : IDL.Func([DoseLog], [], []),
    'saveCallerUserProfile' : IDL.Func([CallerUserProfile], [], []),
    'saveCombineResult' : IDL.Func(
        [
          IDL.Record({
            'bmi' : CombineMeasurement,
            'weight' : CombineMeasurement,
            'passedMedical' : IDL.Bool,
            'height' : CombineMeasurement,
            'powerClean' : CombineMeasurement,
            'verticalJump' : CombineMeasurement,
            'dash10yd' : CombineMeasurement,
            'dash20yd' : CombineMeasurement,
            'dash40yd' : CombineMeasurement,
            'wingspan' : CombineMeasurement,
            'threeConeDrill' : CombineMeasurement,
            'benchPressReps' : CombineMeasurement,
            'squat' : CombineMeasurement,
            'developerNotes' : IDL.Opt(IDL.Text),
            'shuttleProAgility' : CombineMeasurement,
            'shuttle20yd' : CombineMeasurement,
            'shuttle60yd' : CombineMeasurement,
            'makePublic' : IDL.Bool,
            'handSize' : CombineMeasurement,
            'broadJump' : CombineMeasurement,
            'seatedRow' : CombineMeasurement,
            'athleteName' : IDL.Text,
            'armLength' : CombineMeasurement,
            'standingReach' : CombineMeasurement,
            'bodyFatPercentage' : CombineMeasurement,
          }),
        ],
        [CombineResult],
        [],
      ),
    'saveCommitmentsPlan' : IDL.Func([CommitmentsPlan], [], []),
    'saveReflection' : IDL.Func([Reflection], [], []),
    'toggleCombinePublicState' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'togglePaymentStatus' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };