/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CheckIn {
  'stressLevel' : bigint,
  'mood' : string,
  'timestamp' : Time,
  'reflection' : string,
  'workHours' : bigint,
  'intention' : string,
}
export interface CombineResult {
  'id' : bigint,
  'creator' : Principal,
  'dash10yd' : [] | [number],
  'dash20yd' : [] | [number],
  'dash40yd' : [] | [number],
  'heightInches' : [] | [bigint],
  'wingspanInches' : [] | [number],
  'threeConeDrill' : [] | [number],
  'handSizeInches' : [] | [number],
  'weightPounds' : [] | [bigint],
  'benchPressReps' : [] | [bigint],
  'broadJumpInches' : [] | [number],
  'shuttle20yd' : [] | [number],
  'timestamp' : Time,
  'isPublic' : boolean,
  'verticalJumpInches' : [] | [number],
  'athleteName' : string,
}
export interface CommitmentsPlan {
  'thingsToAvoid' : string,
  'atRiskActions' : string,
  'personalCommitments' : string,
}
export interface DoseLog {
  'status' : { 'Skipped' : null } |
    { 'Late' : null } |
    { 'Taken' : null },
  'medicationName' : string,
  'scheduledTime' : string,
  'note' : [] | [string],
  'takenTime' : [] | [Time],
  'timestamp' : Time,
}
export interface EmergencyContact {
  'relationship' : string,
  'name' : string,
  'notes' : string,
  'phone' : string,
}
export interface Medication {
  'endDate' : [] | [Time],
  'dose' : string,
  'name' : string,
  'instructions' : string,
  'schedule' : Array<string>,
  'prescriber' : string,
  'startDate' : [] | [Time],
}
export interface Meeting {
  'date' : Time,
  'goals' : string,
  'notes' : string,
  'sponsorContactNotes' : string,
  'format' : string,
}
export interface RecoveryStep {
  'id' : bigint,
  'title' : string,
  'completed' : boolean,
  'description' : string,
}
export interface Reflection {
  'id' : bigint,
  'stepId' : bigint,
  'content' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmergencyContact' : ActorMethod<[EmergencyContact], undefined>,
  'addMedication' : ActorMethod<[Medication], undefined>,
  'addMeeting' : ActorMethod<[Meeting], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCombineResult' : ActorMethod<[bigint], boolean>,
  'getAllPublicCombineEntries' : ActorMethod<[], Array<CombineResult>>,
  'getAllRecoverySteps' : ActorMethod<[], Array<RecoveryStep>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckIns' : ActorMethod<[], Array<CheckIn>>,
  'getCombineResultById' : ActorMethod<[bigint], [] | [CombineResult]>,
  'getCommitmentsPlan' : ActorMethod<[], [] | [CommitmentsPlan]>,
  'getDoseLogs' : ActorMethod<[], Array<DoseLog>>,
  'getEmergencyContacts' : ActorMethod<[], Array<EmergencyContact>>,
  'getMedications' : ActorMethod<[], Array<Medication>>,
  'getMeetings' : ActorMethod<[], Array<Meeting>>,
  'getReflections' : ActorMethod<[], Array<Reflection>>,
  'getUserCombineResults' : ActorMethod<[Principal], Array<CombineResult>>,
  'getUserData' : ActorMethod<
    [],
    {
      'meetings' : Array<Meeting>,
      'emergencyContacts' : Array<EmergencyContact>,
      'reflections' : Array<Reflection>,
      'medications' : Array<Medication>,
      'checkIns' : Array<CheckIn>,
      'doseLogs' : Array<DoseLog>,
      'commitmentsPlan' : [] | [CommitmentsPlan],
      'recoverySteps' : Array<RecoveryStep>,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logCheckIn' : ActorMethod<[CheckIn], undefined>,
  'logDose' : ActorMethod<[DoseLog], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCombineResult' : ActorMethod<
    [
      {
        'dash10yd' : [] | [number],
        'dash20yd' : [] | [number],
        'dash40yd' : [] | [number],
        'heightInches' : [] | [bigint],
        'wingspanInches' : [] | [number],
        'threeConeDrill' : [] | [number],
        'handSizeInches' : [] | [number],
        'weightPounds' : [] | [bigint],
        'benchPressReps' : [] | [bigint],
        'broadJumpInches' : [] | [number],
        'shuttle20yd' : [] | [number],
        'makePublic' : boolean,
        'verticalJumpInches' : [] | [number],
        'athleteName' : string,
      },
    ],
    CombineResult
  >,
  'saveCommitmentsPlan' : ActorMethod<[CommitmentsPlan], undefined>,
  'saveReflection' : ActorMethod<[Reflection], undefined>,
  'toggleCombinePublicState' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];