/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CommitmentsPlan {
    thingsToAvoid: string;
    atRiskActions: string;
    personalCommitments: string;
}
export interface CheckIn {
    stressLevel: bigint;
    mood: string;
    timestamp: Time;
    reflection: string;
    workHours: bigint;
    intention: string;
}
export interface RecoveryStep {
    id: bigint;
    title: string;
    completed: boolean;
    description: string;
}
export type Time = bigint;
export interface Meeting {
    date: Time;
    goals: string;
    notes: string;
    sponsorContactNotes: string;
    format: string;
}
export interface EmergencyContact {
    relationship: string;
    name: string;
    notes: string;
    phone: string;
}
export interface Reflection {
    id: bigint;
    stepId: bigint;
    content: string;
    timestamp: Time;
}
export interface DoseLog {
    status: Variant_Skipped_Late_Taken;
    medicationName: string;
    scheduledTime: string;
    note?: string;
    takenTime?: Time;
    timestamp: Time;
}
export interface UserProfile {
    name: string;
}
export interface Medication {
    endDate?: Time;
    dose: string;
    name: string;
    instructions: string;
    schedule: Array<string>;
    prescriber: string;
    startDate?: Time;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_Skipped_Late_Taken {
    Skipped = "Skipped",
    Late = "Late",
    Taken = "Taken"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEmergencyContact(contact: EmergencyContact): Promise<void>;
    addMedication(medicine: Medication): Promise<void>;
    addMeeting(meeting: Meeting): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllRecoverySteps(): Promise<Array<RecoveryStep>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCheckIns(): Promise<Array<CheckIn>>;
    getCommitmentsPlan(): Promise<CommitmentsPlan | null>;
    getDoseLogs(): Promise<Array<DoseLog>>;
    getEmergencyContacts(): Promise<Array<EmergencyContact>>;
    getMedications(): Promise<Array<Medication>>;
    getMeetings(): Promise<Array<Meeting>>;
    getReflections(): Promise<Array<Reflection>>;
    getUserData(): Promise<{
        meetings: Array<Meeting>;
        emergencyContacts: Array<EmergencyContact>;
        reflections: Array<Reflection>;
        medications: Array<Medication>;
        checkIns: Array<CheckIn>;
        doseLogs: Array<DoseLog>;
        commitmentsPlan?: CommitmentsPlan;
        recoverySteps: Array<RecoveryStep>;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logCheckIn(checkIn: CheckIn): Promise<void>;
    logDose(doseLog: DoseLog): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCommitmentsPlan(plan: CommitmentsPlan): Promise<void>;
    saveReflection(reflection: Reflection): Promise<void>;
}
import type { CheckIn as _CheckIn, CommitmentsPlan as _CommitmentsPlan, DoseLog as _DoseLog, EmergencyContact as _EmergencyContact, Medication as _Medication, Meeting as _Meeting, RecoveryStep as _RecoveryStep, Reflection as _Reflection, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEmergencyContact(arg0: EmergencyContact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmergencyContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmergencyContact(arg0);
            return result;
        }
    }
    async addMedication(arg0: Medication): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedication(to_candid_Medication_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedication(to_candid_Medication_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMeeting(arg0: Meeting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeeting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeeting(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllRecoverySteps(): Promise<Array<RecoveryStep>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecoverySteps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecoverySteps();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckIns(): Promise<Array<CheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckIns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckIns();
            return result;
        }
    }
    async getCommitmentsPlan(): Promise<CommitmentsPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommitmentsPlan();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommitmentsPlan();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoseLogs(): Promise<Array<DoseLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoseLogs();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoseLogs();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmergencyContacts(): Promise<Array<EmergencyContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyContacts();
            return result;
        }
    }
    async getMedications(): Promise<Array<Medication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedications();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedications();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeetings(): Promise<Array<Meeting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeetings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeetings();
            return result;
        }
    }
    async getReflections(): Promise<Array<Reflection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReflections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReflections();
            return result;
        }
    }
    async getUserData(): Promise<{
        meetings: Array<Meeting>;
        emergencyContacts: Array<EmergencyContact>;
        reflections: Array<Reflection>;
        medications: Array<Medication>;
        checkIns: Array<CheckIn>;
        doseLogs: Array<DoseLog>;
        commitmentsPlan?: CommitmentsPlan;
        recoverySteps: Array<RecoveryStep>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserData();
                return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserData();
            return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logCheckIn(arg0: CheckIn): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logCheckIn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logCheckIn(arg0);
            return result;
        }
    }
    async logDose(arg0: DoseLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logDose(to_candid_DoseLog_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDose(to_candid_DoseLog_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCommitmentsPlan(arg0: CommitmentsPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCommitmentsPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCommitmentsPlan(arg0);
            return result;
        }
    }
    async saveReflection(arg0: Reflection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReflection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReflection(arg0);
            return result;
        }
    }
}
function from_candid_DoseLog_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoseLog): DoseLog {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Medication_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Medication): Medication {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommitmentsPlan]): CommitmentsPlan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        Skipped: null;
    } | {
        Late: null;
    } | {
        Taken: null;
    };
    medicationName: string;
    scheduledTime: string;
    note: [] | [string];
    takenTime: [] | [_Time];
    timestamp: _Time;
}): {
    status: Variant_Skipped_Late_Taken;
    medicationName: string;
    scheduledTime: string;
    note?: string;
    takenTime?: Time;
    timestamp: Time;
} {
    return {
        status: from_candid_variant_n12(_uploadFile, _downloadFile, value.status),
        medicationName: value.medicationName,
        scheduledTime: value.scheduledTime,
        note: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.note)),
        takenTime: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.takenTime)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: [] | [_Time];
    dose: string;
    name: string;
    instructions: string;
    schedule: Array<string>;
    prescriber: string;
    startDate: [] | [_Time];
}): {
    endDate?: Time;
    dose: string;
    name: string;
    instructions: string;
    schedule: Array<string>;
    prescriber: string;
    startDate?: Time;
} {
    return {
        endDate: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.endDate)),
        dose: value.dose,
        name: value.name,
        instructions: value.instructions,
        schedule: value.schedule,
        prescriber: value.prescriber,
        startDate: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.startDate))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meetings: Array<_Meeting>;
    emergencyContacts: Array<_EmergencyContact>;
    reflections: Array<_Reflection>;
    medications: Array<_Medication>;
    checkIns: Array<_CheckIn>;
    doseLogs: Array<_DoseLog>;
    commitmentsPlan: [] | [_CommitmentsPlan];
    recoverySteps: Array<_RecoveryStep>;
}): {
    meetings: Array<Meeting>;
    emergencyContacts: Array<EmergencyContact>;
    reflections: Array<Reflection>;
    medications: Array<Medication>;
    checkIns: Array<CheckIn>;
    doseLogs: Array<DoseLog>;
    commitmentsPlan?: CommitmentsPlan;
    recoverySteps: Array<RecoveryStep>;
} {
    return {
        meetings: value.meetings,
        emergencyContacts: value.emergencyContacts,
        reflections: value.reflections,
        medications: from_candid_vec_n15(_uploadFile, _downloadFile, value.medications),
        checkIns: value.checkIns,
        doseLogs: from_candid_vec_n9(_uploadFile, _downloadFile, value.doseLogs),
        commitmentsPlan: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.commitmentsPlan)),
        recoverySteps: value.recoverySteps
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Skipped: null;
} | {
    Late: null;
} | {
    Taken: null;
}): Variant_Skipped_Late_Taken {
    return "Skipped" in value ? Variant_Skipped_Late_Taken.Skipped : "Late" in value ? Variant_Skipped_Late_Taken.Late : "Taken" in value ? Variant_Skipped_Late_Taken.Taken : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Medication>): Array<Medication> {
    return value.map((x)=>from_candid_Medication_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DoseLog>): Array<DoseLog> {
    return value.map((x)=>from_candid_DoseLog_n10(_uploadFile, _downloadFile, x));
}
function to_candid_DoseLog_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoseLog): _DoseLog {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Medication_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Medication): _Medication {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: Time;
    dose: string;
    name: string;
    instructions: string;
    schedule: Array<string>;
    prescriber: string;
    startDate?: Time;
}): {
    endDate: [] | [_Time];
    dose: string;
    name: string;
    instructions: string;
    schedule: Array<string>;
    prescriber: string;
    startDate: [] | [_Time];
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        dose: value.dose,
        name: value.name,
        instructions: value.instructions,
        schedule: value.schedule,
        prescriber: value.prescriber,
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Variant_Skipped_Late_Taken;
    medicationName: string;
    scheduledTime: string;
    note?: string;
    takenTime?: Time;
    timestamp: Time;
}): {
    status: {
        Skipped: null;
    } | {
        Late: null;
    } | {
        Taken: null;
    };
    medicationName: string;
    scheduledTime: string;
    note: [] | [string];
    takenTime: [] | [_Time];
    timestamp: _Time;
} {
    return {
        status: to_candid_variant_n21(_uploadFile, _downloadFile, value.status),
        medicationName: value.medicationName,
        scheduledTime: value.scheduledTime,
        note: value.note ? candid_some(value.note) : candid_none(),
        takenTime: value.takenTime ? candid_some(value.takenTime) : candid_none(),
        timestamp: value.timestamp
    };
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Skipped_Late_Taken): {
    Skipped: null;
} | {
    Late: null;
} | {
    Taken: null;
} {
    return value == Variant_Skipped_Late_Taken.Skipped ? {
        Skipped: null
    } : value == Variant_Skipped_Late_Taken.Late ? {
        Late: null
    } : value == Variant_Skipped_Late_Taken.Taken ? {
        Taken: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
